name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  dio: ^5.7.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  google_mlkit_pose_detection: ^0.13.0
  camera: ^0.11.0+2
  sensors_plus: ^6.1.1
  image: ^4.0.17
  change_app_package_name: ^1.4.0
  intl: ^0.20.2
  audioplayers: ^6.1.1
  flutter_tts: ^4.2.2
  firebase_core: ^3.11.0
  http: ^1.3.0
  jwt_decoder: ^2.0.1
  path: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo2.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/sound/alert.aac
    - assets/image.jpeg
    - assets/splashscreen.png
    - assets/imagehome.jpg

