class Autogenerated {
  String? firstname;
  String? lastname;
  String? username;
  String? password;
  String? email;

  Autogenerated(
      {this.firstname,
      this.lastname,
      this.username,
      this.password,
      this.email});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    firstname = json['firstname'];
    lastname = json['lastname'];
    username = json['username'];
    password = json['password'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['username'] = username;
    data['password'] = password;
    data['email'] = email;
    return data;
  }
}
