import 'dart:convert';
import 'package:flutter_application_1/Data/Modals/datas.dart';
import 'package:flutter_application_1/Data/Modals/json.dart';


fetchDataWithoutAPI() {
  // Example JSON data for a single object
  return Autogenerated.fromJson(jsonDecode(dataJson) as Map<String, dynamic>);
}

// Function to fetch a list of data objects without an API
List<Autogenerated> fetchDataListWithoutAPI() {
  // Example JSON data for a list of objects
  List<dynamic> decodedJson = jsonDecode(dataJsonList);
  return decodedJson
      .map((json) => Autogenerated.fromJson(json as Map<String, dynamic>))
      .toList();
}
